/**
 * Generates src/version.ts from package.json's version field — the single
 * source of truth. Regenerated by `build`/`dev`; never edit src/version.ts
 * by hand (it is gitignored).
 *
 * Deliberately NOT a runtime `import package.json` in src/index.ts: an ESM
 * JSON import (`with { type: "json" }` / the older `assert` form) has
 * required different syntax across Node versions and would tie this
 * package's minimum supported Node version to whichever import-assertion
 * syntax is chosen. Generating a plain .ts constant at build time avoids
 * that entirely and adds nothing to the published package beyond what
 * already ships in dist/.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf-8"));

const content =
  "// AUTO-GENERATED by scripts/sync-version.mjs from package.json's \"version\" field.\n" +
  "// Do not edit by hand — it is regenerated by `npm run build` / `npm run dev` and gitignored.\n" +
  `export const VERSION = ${JSON.stringify(pkg.version)};\n`;

writeFileSync(join(repoRoot, "src", "version.ts"), content);
// stderr, not stdout: some callers (e.g. `npm pack --json`, via the prepack
// lifecycle this script runs under) parse this process's stdout as data.
console.error(`sync-version: src/version.ts = ${pkg.version}`);
